CORENAME: LEO # 芯片型号 LEO/LEO_MPW
PB_FILE: intent_model.pb # 输入的pb文件
OUTPUT_FILE: intent.npu # 输出的NPU文件名
NPU_UNIT: NPU64 # NPU设备类型
COMPRESS: true # 压缩模型
COMPRESS_QUANT_BITS: 8 # 量化成8bits
COMPRESS_TYPE: LINEAR # 线性压缩
OUTPUT_TYPE: raw # NPU文件的类型
INPUT_OPS:
    model_intent/context: [1, 200] # 输入结点名称和数据维度，每运行一次
    model_intent/query: [1,30]
    model_intent/context_pe: [1, 200, 300]
    model_intent/query_pe: [1,30, 300]
	
OUTPUT_OPS: [model_intent/intent_score]
